---
services:
  bledom-controller:
    build: .
    image: localhost/bledom-controller
    container_name: bledom-controller
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./patterns:/app/patterns
      - ./static:/app/static
      - ./schedules.json:/app/schedules.json
      - ./config.json:/app/config.json
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bledom.rule=Host(`bledom.home.local`)"
      - "traefik.http.services.bledom.loadbalancer.server.port=8080"
    networks:
      - traefik

networks:
  traefik:
    external: true

